---
abstract: "join multiple \"events\" into one"
author:
  - 'Jonathan Rockway C<< <jrockway@cpan.org> >>'
build_requires:
  Test::More: 0
  ok: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Event-Join
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  MooseX::AttributeHelpers: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
